---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    {{ cookiecutter.role_name }}_base_dir: /opt/{{ cookiecutter.role_name }}
  pre_tasks:
    - name: Install Docker (for Docker Compose roles)
      ansible.builtin.shell: |
        curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker
  roles:
    - role: {{ cookiecutter.role_name }}
